name: Deploy WordPress

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20.16.0'
           cache: 'npm'
        cache-dependency-path: 'Wordpressproject/package-lock.json' 

    - name: Install dependencies
      run: npm install

    - name: Build assets
      run: npm run build
      
    - name: Install Yarn
        run: npm install -g yarn

      - name: Install dependencies and generate yarn.lock
        run: yarn install

       name: Install dependencies
      run: npm ci  # Use 'npm ci' for clean install using package-lock.json
        

      - name: Commit and push yarn.lock
        run: |
          git config --global user.name 'rafael19899'
          git config --global user.email 'rafael_alberto100@hotmail.com'
          git add yarn.lock
          git commit -m 'Generate yarn.lock file'
          git push

    - name: Deploy to server
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        SERVER_USER: ${{ secrets.SERVER_USER }}
        SERVER_IP: ${{ secrets.SERVER_IP }}
      run: |
        echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
        rsync -avz --exclude 'node_modules' --exclude '.git' . $SERVER_USER@$SERVER_IP:/path/to/your/project
